
sample :drum_cymbal_closed
sample :drum_bass_hard
sleep 0.25
sample :drum_bass_hard
sleep 0.25
sample :drum_cymbal_closed
sleep 0.5
sample :drum_tom_lo_hard
sample :drum_tom_hi_hard
sleep 0.25
sample :drum_tom_hi_soft
sample :drum_tom_lo_soft
sleep 0.125
sample :drum_tom_mid_soft
sample :drum_bass_hard
sleep 0.125
sample :drum_tom_lo_hard
sample :drum_tom_hi_hard
sleep 0.125
sample :drum_tom_mid_soft
sample :drum_bass_hard
sleep 0.125
sample :drum_tom_lo_hard
sample :drum_tom_hi_hard
sleep 0.125
sample :drum_tom_mid_soft
sample :drum_bass_hard
sleep 0.125